# Generated by Django 3.1.4 on 2020-12-31 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201230_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemasText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sentence_amount', models.IntegerField(default=5)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schemas')),
            ],
        ),
        migrations.CreateModel(
            name='SchemasPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schemas')),
            ],
        ),
        migrations.CreateModel(
            name='SchemasInteger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('min_integer', models.IntegerField(default=18)),
                ('max_integer', models.IntegerField(default=60)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schemas')),
            ],
        ),
        migrations.CreateModel(
            name='SchemasFullName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schemas')),
            ],
        ),
        migrations.CreateModel(
            name='SchemasEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schemas')),
            ],
        ),
    ]
