# Generated by Django 3.1.4 on 2021-01-01 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_schemasemail_schemasfullname_schemasinteger_schemasphonenumber_schemastext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemasColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('min_integer', models.IntegerField(default=18)),
                ('max_integer', models.IntegerField(default=60)),
                ('sentence_amount', models.IntegerField(default=5)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schemas')),
            ],
        ),
        migrations.RemoveField(
            model_name='schemasfullname',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='schemasinteger',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='schemasphonenumber',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='schemastext',
            name='schema',
        ),
        migrations.DeleteModel(
            name='SchemasEmail',
        ),
        migrations.DeleteModel(
            name='SchemasFullName',
        ),
        migrations.DeleteModel(
            name='SchemasInteger',
        ),
        migrations.DeleteModel(
            name='SchemasPhoneNumber',
        ),
        migrations.DeleteModel(
            name='SchemasText',
        ),
    ]
