# Generated by Django 3.1.4 on 2021-01-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210101_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemascolumn',
            name='category',
            field=models.CharField(choices=[('full_name', 'Full name'), ('email', 'Email'), ('phone_number', 'Phone number'), ('integer', 'Integer'), ('text', 'Text')], default='full_name', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schemascolumn',
            name='max_integer',
            field=models.IntegerField(blank=True, default=60),
        ),
        migrations.AlterField(
            model_name='schemascolumn',
            name='min_integer',
            field=models.IntegerField(blank=True, default=18),
        ),
        migrations.AlterField(
            model_name='schemascolumn',
            name='sentence_amount',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
