# Generated by Django 3.1.4 on 2021-01-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210101_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemascolumn',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
