# Generated by Django 3.1.4 on 2021-01-02 13:53

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_datasets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasets',
            name='file',
            field=models.FileField(blank=True, upload_to=main.models.user_directory_path),
        ),
    ]
