# Generated by Django 3.1.4 on 2021-01-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_datasets_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemas',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='schemas',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique name for every user'),
        ),
    ]
