# Generated by Django 3.1.4 on 2021-01-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210103_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemas',
            options={'verbose_name': 'Schema', 'verbose_name_plural': 'Schemas'},
        ),
    ]
