# Generated by Django 3.1.4 on 2021-01-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210103_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasets',
            options={'verbose_name': 'Data set', 'verbose_name_plural': 'Data sets'},
        ),
        migrations.AlterModelOptions(
            name='schemascolumn',
            options={'verbose_name': 'Schemas column', 'verbose_name_plural': 'Schemas columns'},
        ),
    ]
